name: Upload to Chrome Web Store

on: 
  push:
    tags:
      -'*'


jobs:
  upload:
    run-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: check current 
      run: ls -la
    - name: show current directory 
      run: pwd